### ISSUE TITLE
PointerIndexOutOfRange

### ISSUE THREAD

**Issue by ghost** [jjhesk/LoyalNativeSlider#41]
In zoom activity when i pinch in till the last it shows this error.
And Application stops after this error.
Please give me some solution for this error

This is my log:

03-09 17:01:47.544 21673-21673/com.hkm.loyalns E/InputEventReceiver: Exception dispatching input event.
03-09 17:01:47.549 21673-21673/com.hkm.loyalns D/AndroidRuntime: Shutting down VM
03-09 17:01:47.556 21673-21673/com.hkm.loyalns E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.hkm.loyalns, PID: 21673
                                                                 java.lang.IllegalArgumentException: pointerIndex out of range
                                                                     at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                     at android.view.MotionEvent.getX(MotionEvent.java:2014)
                                                                     at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
                                                                     at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
                                                                     at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
                                                                     at com.hkm.slider.Tricks.ViewPagerEx.onInterceptTouchEvent(ViewPagerEx.java:1886)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:2752)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                     at android.view.View.dispatchPointerEvent(View.java:8671)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912)
                                                                     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851)
                                                                     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822)
                                                                     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6002)
                                                                     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventRecei

**Comment by horaciosolorio** [comment]
I have have same issue please help us

you only need to catch the IllegalArgumentException in the onInterceptTouchEvent.

**Comment by jjhesk** [comment]
the zoom in component has alot of issues so that i removed that one and put another one on it but this one is more simple.

**Comment by cresttechhead** [comment]
when will you release latest update for checking that

**Comment by jjhesk** [comment]
first of all i need to find the perfect or less bugs library that will support those motion gesture then i can integrate it into the current library. let me know if u have some suggestions.

**Comment by ghost** [comment]
I have applied your latest release but it have same issue in zoom view

**Comment by jjhesk** [comment]
if the issue is still happening, please use your own implementation from other zooomview library.
