### ISSUE TITLE
Fatal crash when bindEventShowGlide(v, target);

### ISSUE THREAD

**Issue by azizimusa** [jjhesk/LoyalNativeSlider#42]
I'm extending BaseSliderView and instead of         **bindEventAndShowPicasso(v, target);**
 I'm replacing it with         **bindEventShowGlide(v, target);**

But when running my program. Fatal error occured. Below are the details :

`FATAL EXCEPTION: main
                                                                              Process: com.malldirectory.ioipuchong, PID: 26813
                                                                              java.lang.ClassCastException: java.io.File cannot be cast to java.lang.String
                                                                                  at com.hkm.slider.SliderTypes.BaseSliderView$1.onResourceReady(BaseSliderView.java:335)
                                                                                  at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:522)
                                                                                  at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
                                                                                  at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
                                                                                  at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
                                                                                  at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:4998)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
                                                                                  at dalvik.system.NativeStart.main(Native Method)`

**Comment by azizimusa** [comment]
It turn out. I had to use String for image path rather than converting it to File.

`CustomSliderView textSliderView = new CustomSliderView(getActivity());
                textSliderView
                        .image(string image path)
                        .setScaleType(BaseSliderView.ScaleType.Fit);`

**Comment by jjhesk** [comment]
check the new update for better handling of load images
