### ISSUE TITLE
Resources$NotFoundException on SliderLayout inflating

### ISSUE THREAD

**Issue by YuriHeupa** [jjhesk/LoyalNativeSlider#51]
I'm getting a Resources$NotFoundException while inflating a new SliderLayout, here's the stack trace:

> W/ResourceType: No known package when getting value for resource number 0xff464646
> W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0xff464646
> W/System.err:     at android.content.res.Resources.getValue(Resources.java:1310)
> W/System.err:     at android.content.res.Resources.getValue(Resources.java:1290)
> W/System.err:     at android.content.res.Resources.getColor(Resources.java:948)
> W/System.err:     at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:368)
> W/System.err:     at com.hkm.slider.Indicators.PagerIndicator.setDefaultIndicatorColor(PagerIndicator.java:287)
> W/System.err:     at com.hkm.slider.Indicators.PagerIndicator.<init>(PagerIndicator.java:183)
> W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
> W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
> W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:607)
> W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
> W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
> W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
> W/System.err:     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
> W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
> W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
> W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
> W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
> W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
> W/System.err:     at com.hkm.slider.SliderLayout.<init>(SliderLayout.java:193)
> W/System.err:     at com.hkm.slider.SliderLayout.<init>(SliderLayout.java:187)
> W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
> W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
> W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:607)
> W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
> W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
> W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
> W/System.err:     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
> W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
> W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
> W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
> W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
> W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

The problem is in `PagerIndicator.java:148`:

``` java
mDefaultSelectedColor = attributes.getColor(R.styleable.PagerIndicator_selected_color, Color.rgb(70, 70, 70));
```

The default color is a rgb color if it's not defined in layout, but `PagerIndicator.java:287` retrieve the color from resources:

``` java
final int a = ContextCompat.getColor(mContext, selectedColor);
```

If it's not defined in layout it raises this warning multiple times.

This calls is taking a lot of time to inflate my view, the application is getting ANR's.

**Comment by YuriHeupa** [comment]
This should be fixed with #52.

Hope that get accepted and released soon.
